export { default as DatasetFiltersComponent } from '../../components/feedback-task/DatasetFilters.component.vue'
export { default as FeedbackTaskProgress } from '../../components/feedback-task/FeedbackTaskProgress.vue'
export { default as RadioButtonsSelectBase } from '../../components/feedback-task/RadioButtonsSelect.base.vue'
export { default as RecordFeedbackTaskComponent } from '../../components/feedback-task/RecordFeedbackTask.component.vue'
export { default as SearchBarBase } from '../../components/feedback-task/SearchBar.base.vue'
export { default as StatusFilter } from '../../components/feedback-task/StatusFilter.vue'
export { default as Error } from '../../components/commons/Error.vue'
export { default as PieChart } from '../../components/commons/PieChart.vue'
export { default as TaskSearch } from '../../components/commons/TaskSearch.vue'
export { default as BaseActionTooltip } from '../../components/base/BaseActionTooltip.vue'
export { default as BaseBreadcrumbs } from '../../components/base/BaseBreadcrumbs.vue'
export { default as BaseButton } from '../../components/base/BaseButton.vue'
export { default as BaseCheckbox } from '../../components/base/BaseCheckbox.vue'
export { default as BaseCode } from '../../components/base/BaseCode.vue'
export { default as BaseIconWithBadge } from '../../components/base/BaseIconWithBadge.vue'
export { default as BaseLoading } from '../../components/base/BaseLoading.vue'
export { default as BaseModal } from '../../components/base/BaseModal.vue'
export { default as BaseProgress } from '../../components/base/BaseProgress.vue'
export { default as BaseRange } from '../../components/base/BaseRange.vue'
export { default as BaseSearchBar } from '../../components/base/BaseSearchBar.vue'
export { default as BaseSlider } from '../../components/base/BaseSlider.vue'
export { default as BaseSpinner } from '../../components/base/BaseSpinner.vue'
export { default as BaseSwitch } from '../../components/base/BaseSwitch.vue'
export { default as BaseTag } from '../../components/base/BaseTag.vue'
export { default as BaseTopbarBrand } from '../../components/base/BaseTopbarBrand.vue'
export { default as DatasetsTable } from '../../components/features/datasets/DatasetsTable.vue'
export { default as UserAvatarTooltip } from '../../components/features/user/UserAvatarTooltip.vue'
export { default as TextFieldComponent } from '../../components/feedback-task/field/TextField.component.vue'
export { default as PaginationComponent } from '../../components/feedback-task/footer/Pagination.component.vue'
export { default as PaginationFeedbackTaskComponent } from '../../components/feedback-task/footer/PaginationFeedbackTask.component.vue'
export { default as DatasetDeleteComponent } from '../../components/commons/dataset-deletion/DatasetDelete.component.vue'
export { default as DatasetDeleteFeedbackTaskComponent } from '../../components/commons/dataset-deletion-feedback-task/DatasetDeleteFeedbackTask.component.vue'
export { default as DatasetDescriptionComponent } from '../../components/commons/dataset-description/DatasetDescription.component.vue'
export { default as DatasetTrainComponent } from '../../components/commons/dataset-train/DatasetTrain.component.vue'
export { default as DatasetsEmpty } from '../../components/commons/datasets-list/DatasetsEmpty.vue'
export { default as EditionLabelComponent } from '../../components/commons/edition-label/EditionLabel.component.vue'
export { default as TextClassificationGlobalLabelsComponent } from '../../components/commons/edition-label/TextClassificationGlobalLabels.component.vue'
export { default as TokenClassificationGlobalLabelsComponent } from '../../components/commons/edition-label/TokenClassificationGlobalLabels.component.vue'
export { default as EditionUserInfoComponent } from '../../components/commons/edition-user-info/EditionUserInfo.component.vue'
export { default as DatasetSettingsIcon } from '../../components/commons/header/DatasetSettingsIcon.vue'
export { default as HeaderComponent } from '../../components/commons/header/Header.component.vue'
export { default as LoadingLine } from '../../components/commons/header/LoadingLine.vue'
export { default as AppHeader } from '../../components/commons/header/appHeader.vue'
export { default as LoginImageBg } from '../../components/commons/login/LoginImageBg.vue'
export { default as RecordActionButtons } from '../../components/commons/results/RecordActionButtons.vue'
export { default as RecordExtraActions } from '../../components/commons/results/RecordExtraActions.vue'
export { default as RecordInfo } from '../../components/commons/results/RecordInfo.vue'
export { default as Results } from '../../components/commons/results/Results.vue'
export { default as ResultsEmpty } from '../../components/commons/results/ResultsEmpty.vue'
export { default as ResultsList } from '../../components/commons/results/ResultsList.vue'
export { default as ResultsLoading } from '../../components/commons/results/ResultsLoading.vue'
export { default as ResultsRecord } from '../../components/commons/results/ResultsRecord.vue'
export { default as StatusTag } from '../../components/commons/results/StatusTag.vue'
export { default as SidebarButton } from '../../components/commons/sidebar/SidebarButton.vue'
export { default as SidebarMenu } from '../../components/commons/sidebar/SidebarMenu.vue'
export { default as SidebarPanel } from '../../components/commons/sidebar/SidebarPanel.vue'
export { default as SidebarProgress } from '../../components/commons/sidebar/SidebarProgress.vue'
export { default as StatsSelector } from '../../components/commons/sidebar/StatsSelector.vue'
export { default as TaskSidebar } from '../../components/commons/sidebar/TaskSidebar.vue'
export { default as IconButton } from '../../components/commons/sidebar-feedback-task/IconButton.vue'
export { default as SidebarFeedbackTaskComponent } from '../../components/commons/sidebar-feedback-task/SidebarFeedbackTask.component.vue'
export { default as SidebarFeedbackTask } from '../../components/commons/sidebar-feedback-task/SidebarFeedbackTask.vue'
export { default as SidebarFeedbackTaskButtonGroup } from '../../components/commons/sidebar-feedback-task/SidebarFeedbackTaskButtonGroup.vue'
export { default as SidebarFeedbackTaskPanel } from '../../components/commons/sidebar-feedback-task/SidebarFeedbackTaskPanel.vue'
export { default as SidebarFeedbackTaskProgress } from '../../components/commons/sidebar-feedback-task/SidebarFeedbackTaskProgress.vue'
export { default as UserTokenComponent } from '../../components/commons/user-token/UserToken.component.vue'
export { default as BaseInput } from '../../components/base/BaseInputContainer/BaseInput.vue'
export { default as BaseInputContainer } from '../../components/base/BaseInputContainer/BaseInputContainer.vue'
export { default as BaseFeedbackComponent } from '../../components/base/base-feedback/BaseFeedback.component.vue'
export { default as Toast } from '../../components/base/BaseToast/Toast.vue'
export { default as BaseIcon } from '../../components/base/base-icon/BaseIcon.vue'
export { default as BaseTabs } from '../../components/base/base-tabs/BaseTabs.vue'
export { default as BaseCard } from '../../components/base/card/BaseCard.vue'
export { default as DocumentationViewer } from '../../components/base/documentation-viewer/DocumentationViewer.vue'
export { default as BaseDropdown } from '../../components/base/dropdown/BaseDropdown.vue'
export { default as BaseDate } from '../../components/base/format/BaseDate.vue'
export { default as GeometricShapeA } from '../../components/base/geometric-shapes/GeometricShapeA.vue'
export { default as BrandIcon } from '../../components/base/logos/BrandIcon.vue'
export { default as BrandLogo } from '../../components/base/logos/BrandLogo.vue'
export { default as BasePagination } from '../../components/base/pagination/BasePagination.vue'
export { default as BaseRadioButton } from '../../components/base/radio-button/BaseRadioButton.vue'
export { default as RenderMarkdownBaseComponent } from '../../components/base/render-markdown/RenderMarkdown.base.component.vue'
export { default as BaseTableInfo } from '../../components/base/table/BaseTableInfo.vue'
export { default as TableFiltrableColumn } from '../../components/base/table/TableFiltrableColumn.vue'
export { default as TooltipComponent } from '../../components/base/tooltip/Tooltip.component.vue'
export { default as RecordFeedbackTaskAndQuestionnaireContent } from '../../components/page-contents/feedback-task-content/RecordFeedbackTaskAndQuestionnaire.content.vue'
export { default as Text2TextHeader } from '../../components/text2text/header/Text2TextHeader.vue'
export { default as ContentEditableFeedbackTask } from '../../components/text2text/results/ContentEditableFeedbackTask.vue'
export { default as RecordStringText2Text } from '../../components/text2text/results/RecordStringText2Text.vue'
export { default as RecordText2Text } from '../../components/text2text/results/RecordText2Text.vue'
export { default as Text2TextContentEditable } from '../../components/text2text/results/Text2TextContentEditable.vue'
export { default as Text2TextList } from '../../components/text2text/results/Text2TextList.vue'
export { default as Text2TextPredictions } from '../../components/text2text/results/Text2TextPredictions.vue'
export { default as Text2TextResultsList } from '../../components/text2text/results/Text2TextResultsList.vue'
export { default as Text2TextProgress } from '../../components/text2text/sidebar/Text2TextProgress.vue'
export { default as Text2TextSidebar } from '../../components/text2text/sidebar/Text2TextSidebar.vue'
export { default as Text2TextStats } from '../../components/text2text/sidebar/Text2TextStats.vue'
export { default as TextClassificationHeader } from '../../components/text-classifier/header/TextClassificationHeader.vue'
export { default as RuleDefinition } from '../../components/text-classifier/labeling-rules/RuleDefinition.vue'
export { default as RuleEmptyQuery } from '../../components/text-classifier/labeling-rules/RuleEmptyQuery.vue'
export { default as RuleLabelsDefinition } from '../../components/text-classifier/labeling-rules/RuleLabelsDefinition.vue'
export { default as RulesManagement } from '../../components/text-classifier/labeling-rules/RulesManagement.vue'
export { default as RulesMetrics } from '../../components/text-classifier/labeling-rules/RulesMetrics.vue'
export { default as TextClassificationProgress } from '../../components/text-classifier/sidebar/TextClassificationProgress.vue'
export { default as TextClassificationRules } from '../../components/text-classifier/sidebar/TextClassificationRules.vue'
export { default as TextClassificationSidebar } from '../../components/text-classifier/sidebar/TextClassificationSidebar.vue'
export { default as TextClassificationStats } from '../../components/text-classifier/sidebar/TextClassificationStats.vue'
export { default as ClassifierExplorationArea } from '../../components/text-classifier/results/ClassifierExplorationArea.vue'
export { default as LabelPill } from '../../components/text-classifier/results/LabelPill.vue'
export { default as LabelSearch } from '../../components/text-classifier/results/LabelSearch.vue'
export { default as RecordExplain } from '../../components/text-classifier/results/RecordExplain.vue'
export { default as RecordInputs } from '../../components/text-classifier/results/RecordInputs.vue'
export { default as RecordString } from '../../components/text-classifier/results/RecordString.vue'
export { default as RecordTextClassification } from '../../components/text-classifier/results/RecordTextClassification.vue'
export { default as TextClassificationResultsList } from '../../components/text-classifier/results/TextClassificationResultsList.vue'
export { default as EntityLabel } from '../../components/token-classifier/commons/EntityLabel.vue'
export { default as EntitiesHeader } from '../../components/token-classifier/header/EntitiesHeader.vue'
export { default as TokenClassificationHeader } from '../../components/token-classifier/header/TokenClassificationHeader.vue'
export { default as EntitiesSelector } from '../../components/token-classifier/results/EntitiesSelector.vue'
export { default as EntityHighlight } from '../../components/token-classifier/results/EntityHighlight.vue'
export { default as RecordTokenClassification } from '../../components/token-classifier/results/RecordTokenClassification.vue'
export { default as TextSpan } from '../../components/token-classifier/results/TextSpan.vue'
export { default as TextSpanStatic } from '../../components/token-classifier/results/TextSpanStatic.vue'
export { default as TextSpanTooltip } from '../../components/token-classifier/results/TextSpanTooltip.vue'
export { default as TextSpans } from '../../components/token-classifier/results/TextSpans.vue'
export { default as TextSpansStatic } from '../../components/token-classifier/results/TextSpansStatic.vue'
export { default as TokenClassificationResultsList } from '../../components/token-classifier/results/TokenClassificationResultsList.vue'
export { default as SidebarCollapsableMentions } from '../../components/token-classifier/sidebar/SidebarCollapsableMentions.vue'
export { default as TokenClassificationProgress } from '../../components/token-classifier/sidebar/TokenClassificationProgress.vue'
export { default as TokenClassificationSidebar } from '../../components/token-classifier/sidebar/TokenClassificationSidebar.vue'
export { default as TokenClassificationStats } from '../../components/token-classifier/sidebar/TokenClassificationStats.vue'
export { default as LeftDatasetSettingsFeedbackTaskContent } from '../../components/features/dataset/dataset-settings/LeftDatasetSettingsFeedbackTask.content.vue'
export { default as TopDatasetSettingsFeedbackTaskContent } from '../../components/features/dataset/dataset-settings/TopDatasetSettingsFeedbackTask.content.vue'
export { default as LeftDatasetSettingsContent } from '../../components/features/datasets/datasets-settings/LeftDatasetSettings.content.vue'
export { default as TopDatasetSettingsContent } from '../../components/features/datasets/datasets-settings/TopDatasetSettings.content.vue'
export { default as HeaderUserSettingsContent } from '../../components/features/user/user-settings/HeaderUserSettings.content.vue'
export { default as LeftUserSettingsContent } from '../../components/features/user/user-settings/LeftUserSettings.content.vue'
export { default as TopUserSettingsContent } from '../../components/features/user/user-settings/TopUserSettings.content.vue'
export { default as QuestionsFormComponent } from '../../components/commons/forms/questions-form/QuestionsForm.component.vue'
export { default as FilterDropdown } from '../../components/commons/header/filters/FilterDropdown.vue'
export { default as FilterScore } from '../../components/commons/header/filters/FilterScore.vue'
export { default as FilterUncoveredByRules } from '../../components/commons/header/filters/FilterUncoveredByRules.vue'
export { default as FiltersArea } from '../../components/commons/header/filters/FiltersArea.vue'
export { default as FiltersList } from '../../components/commons/header/filters/FiltersList.vue'
export { default as FiltersListEmpty } from '../../components/commons/header/filters/FiltersListEmpty.vue'
export { default as SearchBar } from '../../components/commons/header/filters/SearchBar.vue'
export { default as SelectFilter } from '../../components/commons/header/filters/SelectFilter.vue'
export { default as SelectOptions } from '../../components/commons/header/filters/SelectOptions.vue'
export { default as SelectOptionsSearch } from '../../components/commons/header/filters/SelectOptionsSearch.vue'
export { default as SortFilter } from '../../components/commons/header/filters/SortFilter.vue'
export { default as SortList } from '../../components/commons/header/filters/SortList.vue'
export { default as CreateNewAction } from '../../components/commons/header/global-actions/CreateNewAction.vue'
export { default as GlobalActions } from '../../components/commons/header/global-actions/GlobalActions.vue'
export { default as ValidateDiscardAction } from '../../components/commons/header/global-actions/ValidateDiscardAction.vue'
export { default as DatasetSettingsIconFeedbackTaskComponent } from '../../components/commons/header/header-feedback-task/DatasetSettingsIconFeedbackTask.component.vue'
export { default as HeaderFeedbackTaskComponent } from '../../components/commons/header/header-feedback-task/HeaderFeedbackTask.component.vue'
export { default as HelpInfo } from '../../components/commons/header/help-info/HelpInfo.vue'
export { default as HelpInfoContent } from '../../components/commons/header/help-info/HelpInfoContent.vue'
export { default as BaseFeedbackErrorComponent } from '../../components/base/base-feedback/base-feedback-error/BaseFeedbackError.component.vue'
export { default as SimilarityRecordReferenceComponent } from '../../components/commons/results/similarity/SimilarityRecordReference.component.vue'
export { default as SimilaritySearchComponent } from '../../components/commons/results/similarity/SimilaritySearch.component.vue'
export { default as SimilaritySearchContent } from '../../components/commons/results/similarity/SimilaritySearchContent.vue'
export { default as SimilaritySearchFooter } from '../../components/commons/results/similarity/SimilaritySearchFooter.vue'
export { default as TextClassificationBulkAnnotationSingle } from '../../components/text-classifier/header/global-actions/TextClassificationBulkAnnotationSingle.vue'
export { default as ClassifierAnnotationArea } from '../../components/text-classifier/results/classifier-annotation/ClassifierAnnotationArea.vue'
export { default as ClassifierAnnotationButton } from '../../components/text-classifier/results/classifier-annotation/ClassifierAnnotationButton.vue'
export { default as FilterSimilarity } from '../../components/commons/header/filters/similarity/FilterSimilarity.vue'
export { default as BulkAnnotationComponent } from '../../components/commons/header/global-actions/bulk-annotation/BulkAnnotation.component.vue'
export { default as BulkAnnotationFormComponent } from '../../components/commons/header/global-actions/bulk-annotation/BulkAnnotationForm.component.vue'
export { default as HelpInfoExplain } from '../../components/commons/header/help-info/help-info-content/HelpInfoExplain.vue'
export { default as HelpInfoSimilarity } from '../../components/commons/header/help-info/help-info-content/HelpInfoSimilarity.vue'
export { default as TextClassificationBulkAnnotationComponent } from '../../components/text-classifier/header/global-actions/text-classification-bulk-annotation/TextClassificationBulkAnnotation.component.vue'
export { default as MultiLabelComponent } from '../../components/commons/forms/questions-form/fields/multi-label/MultiLabel.component.vue'
export { default as RatingComponent } from '../../components/commons/forms/questions-form/fields/rating/Rating.component.vue'
export { default as RatingMonoSelectionComponent } from '../../components/commons/forms/questions-form/fields/rating/RatingMonoSelection.component.vue'
export { default as RankingComponent } from '../../components/commons/forms/questions-form/fields/ranking/Ranking.component.vue'
export { default as SingleLabelComponent } from '../../components/commons/forms/questions-form/fields/single-label/SingleLabel.component.vue'
export { default as TextAreaComponent } from '../../components/commons/forms/questions-form/fields/text-area/TextArea.component.vue'
export { default as DndSelectionComponent } from '../../components/commons/forms/questions-form/fields/shared-components/drag-and-drop-selection/DndSelection.component.vue'
export { default as LabelSelectionComponent } from '../../components/commons/forms/questions-form/fields/shared-components/label-selection/LabelSelection.component.vue'
export { default as QuestionHeaderComponent } from '../../components/commons/forms/questions-form/fields/shared-components/question-header/QuestionHeader.component.vue'
export { default as SearchLabelComponent } from '../../components/commons/forms/questions-form/fields/shared-components/search-label/SearchLabel.component.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
